In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.3.4

In [2]:
n_rows = 5
n_cols = 2
cols = ['omset', 'operasional']

df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)), 
                  columns=cols)
df

   omset  operasional
0      6            5
1     16           17
2      5           15
3      6            8
4     10            7

In [3]:
df['omset'] = df['omset'] * 100_000
df['operasional'] = df['operasional'] * 10_000
df

     omset  operasional
0   600000        50000
1  1600000       170000
2   500000       150000
3   600000        80000
4  1000000        70000

In [4]:
n_rows = 365  

df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, 2)), columns=['col1', 'col2'])

df.index = pd.date_range(start='2024-01-01', periods=n_rows, freq='D')

df = df.reset_index().rename(columns={'index': 'tanggal'})

print(df)

       tanggal  col1  col2
0   2024-01-01     8     1
1   2024-01-02    11     9
2   2024-01-03    17    12
3   2024-01-04     5     8
4   2024-01-05    14    12
..         ...   ...   ...
360 2024-12-26     2     7
361 2024-12-27    14     3
362 2024-12-28    10     6
363 2024-12-29    12    19
364 2024-12-30    18    17

[365 rows x 3 columns]

In [5]:
pip install jinja2

Collecting jinja2
  Downloading jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting MarkupSafe>=2.0 (from jinja2)
  Downloading markupsafe-3.0.3-cp312-cp312-win_amd64.whl.metadata (2.8 kB)
Downloading jinja2-3.1.6-py3-none-any.whl (134 kB)
Downloading markupsafe-3.0.3-cp312-cp312-win_amd64.whl (15 kB)
Installing collected packages: MarkupSafe, jinja2
Successfully installed MarkupSafe-3.0.3 jinja2-3.1.6
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
formatku = {'tanggal':'{:%d/%m/%y}', 
            'operasional':'Rp {:.2f}',
            'omset':'Rp {:.2f}'}

laporan = df.style.format(formatku)
laporan

In [7]:
type(laporan)

pandas.io.formats.style.Styler

In [8]:
laporan.set_caption('Data Omset dan Operasional')